"""
Django settings for stock_scraper project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'bkr(1mx&+l80n275l=j6rz!4@qzfb$^-n86xqc*+sj9b*kz9gm')

# Environment detection
IS_FLY = bool(os.environ.get('FLY_ENVIRONMENT') or os.environ.get('FLY_APP_NAME'))
IS_RAILWAY = bool(os.environ.get('RAILWAY_ENVIRONMENT'))
IS_PRODUCTION = IS_FLY or IS_RAILWAY

DEBUG = not IS_PRODUCTION

# Allowed hosts
if IS_FLY:
    # Fly.io domains
    ALLOWED_HOSTS = [
        'stockdata-scraper.fly.dev',
        '*.fly.dev',
        'localhost',
        '127.0.0.1',
        '[::1]',
        '0.0.0.0',
    ]
    # Add Fly.io internal network
    FLY_ALLOC_ID = os.environ.get('FLY_ALLOC_ID')
    if FLY_ALLOC_ID:
        ALLOWED_HOSTS.append(f"{FLY_ALLOC_ID}.vm.{os.environ.get('FLY_APP_NAME', 'stockdata-scraper')}.internal")
elif IS_RAILWAY:
    # Railway domains  
    ALLOWED_HOSTS = [
        'web-production-b236d.up.railway.app',
        '*.railway.app',
        '*.up.railway.app',
        'localhost',
        '127.0.0.1',
        '[::1]',
        '0.0.0.0',
    ]
else:
    # Development
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '0.0.0.0']

CRISPY_TEMPLATE_PACK = "bootstrap4"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'register.apps.RegisterConfig',
    'crispy_forms',
    'django_celery_results',
    'celery_progress',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stock_scraper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stock_scraper.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
if IS_PRODUCTION:
    # Production database (Railway will provide DATABASE_URL)
    DATABASE_URL = os.environ.get('DATABASE_URL')
    if DATABASE_URL:
        # Use provided database (PostgreSQL, MySQL, etc.)
        DATABASES = {
            'default': dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600
            )
        }
    else:
        # Fallback to SQLite for Railway deployment without external database
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': '/tmp/db.sqlite3',  # Use /tmp for writable storage in Railway
            }
        }
else:
    # Local development database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Celery Configuration
USE_CELERY = os.environ.get('USE_CELERY', 'False').lower() == 'true'  # Default to False for easier local dev

if USE_CELERY:
    if IS_PRODUCTION:
        CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379')
    else:
        CELERY_BROKER_URL = 'redis://localhost:6379'
    
    CELERY_RESULT_BACKEND = 'django-db'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'UTC'
else:
    # Disable Celery for deployment testing - tasks run synchronously
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

# Security settings for production
if IS_PRODUCTION:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 86400
    SECURE_REDIRECT_EXEMPT = []
    
    # CSRF trusted origins
    if IS_FLY:
        CSRF_TRUSTED_ORIGINS = [
            'https://stockdata-scraper.fly.dev',
            'https://*.fly.dev',
        ]
    elif IS_RAILWAY:
        CSRF_TRUSTED_ORIGINS = [
            'https://web-production-b236d.up.railway.app',
            'https://*.railway.app',
            'https://*.up.railway.app'
        ]
    
    # Only enable HTTPS redirect if not using platform proxy
    if not (IS_FLY or IS_RAILWAY):
        SECURE_SSL_REDIRECT = True
    
    # Production optimizations for faster startup
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }
    
    # Disable debug toolbar and other dev tools
    DEBUG_TOOLBAR = False
    
    # Optimize database connections
    if 'default' in DATABASES:
        DATABASES['default']['CONN_MAX_AGE'] = 600
        DATABASES['default']['OPTIONS'] = {
            'MAX_CONNS': 20,
            'connect_timeout': 10,
        }

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
