# Fly.io configuration for Stock Data Web App
app = "stockdata-scraper"
primary_region = "sjc"  # San Jose (close to stock markets)

[build]
  dockerfile = "Dockerfile"

[env]
  # Django settings
  DJANGO_SETTINGS_MODULE = "stock_scraper.settings"
  PYTHONUNBUFFERED = "1"
  
  # Chrome optimization for Fly.io
  CHROME_BIN = "/usr/bin/google-chrome-stable"
  CHROMEDRIVER_PATH = "/usr/local/bin/chromedriver"
  
  # Memory optimization
  MALLOC_ARENA_MAX = "2"
  
  # Fly.io environment detection
  FLY_ENVIRONMENT = "true"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  # Keep running for background tasks
  auto_start_machines = true
  min_machines_running = 1
  
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25    # Conservative for 2GB RAM
    soft_limit = 20

[[vm]]
  size = "shared-cpu-2x"  # 2GB RAM, $3.88/month
  memory = "2gb"

[processes]
  web = "gunicorn --bind 0.0.0.0:8000 --workers 1 --threads 2 --timeout 120 --max-requests 100 stock_scraper.wsgi:application"
  worker = "python manage.py celeryd -E --loglevel=info --concurrency=1"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    
  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20
    
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    
  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/health/" 