[phases.install]
# Install Google Chrome and dependencies with robust error handling
cmds = [
    # Update package lists
    "apt-get update",
    
    # Install basic dependencies
    "apt-get install -y wget gnupg unzip curl ca-certificates apt-transport-https software-properties-common",
    
    # Install Google Chrome (simplified approach)
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y google-chrome-stable",
    
    # Install additional dependencies for stealth operation
    "apt-get install -y xvfb fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libnspr4 libnss3 libxss1 libxtst6 libatspi2.0-0 libgtk-3-0 libxdamage1 libdrm2 libxcomposite1 libxrandr2",
    
    # Clean up
    "apt-get clean && rm -rf /var/lib/apt/lists/*",
    
    # Verify Chrome installation
    "which google-chrome-stable && google-chrome-stable --version"
]

[phases.setup]
# Configure environment after successful installation
cmds = [
    "echo 'Chrome installation verified'",
    "google-chrome-stable --version",
    "echo 'ChromeDriver will be managed by WebDriverManager for compatibility'"
]

[variables]
# Environment variables for stealth Chrome operation
CHROME_BIN = "/usr/bin/google-chrome-stable"
DISPLAY = ":99"
# Stealth environment variables
CHROME_NO_SANDBOX = "true"
CHROME_DISABLE_GPU = "true" 