[phases.install]
# Install Chrome and dependencies with proper prerequisites
cmds = [
    # First install basic tools needed for Chrome repository setup
    "apt-get update && apt-get install -y wget gnupg ca-certificates",
    # Add Google Chrome repository and install Chrome with all dependencies
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list && apt-get update && apt-get install -y google-chrome-stable xvfb fonts-liberation libappindicator3-1 libasound2t64 libatk-bridge2.0-0 libnspr4 libnss3 libxss1 libxtst6 libatspi2.0-0 libgtk-3-0 libxdamage1 libdrm2 libxcomposite1 libxrandr2 && apt-get clean && rm -rf /var/lib/apt/lists/*"
]

[phases.setup]
# Verify Chrome installation after packages are installed
cmds = [
    "echo 'Verifying Chrome installation...'",
    "which google-chrome-stable && echo 'Chrome binary found' || echo 'Chrome binary not found'",
    "google-chrome-stable --version && echo 'Chrome version check successful' || echo 'Chrome version check failed'",
    "echo 'ChromeDriver will be managed by WebDriverManager for compatibility'"
]

[variables]
# Environment variables for stealth Chrome operation
CHROME_BIN = "/usr/bin/google-chrome-stable"
DISPLAY = ":99"
# Stealth environment variables
CHROME_NO_SANDBOX = "true"
CHROME_DISABLE_GPU = "true" 