[phases.install]
# Install Chrome and ChromeDriver for Railway deployment
cmds = [
    # Update and install basic dependencies
    "apt-get update && apt-get install -y wget gnupg ca-certificates unzip curl",
    
    # Install Chrome
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update && apt-get install -y google-chrome-stable",
    
    # Verify Chrome installation
    "google-chrome --version || echo 'Chrome installation failed'",
    
    # Install ChromeDriver with version detection and error handling (combined command)
    "CHROME_VERSION=$(google-chrome --version | grep -oP '\\d+' | head -1) && echo \"Detected Chrome major version: $CHROME_VERSION\" && if [ -n \"$CHROME_VERSION\" ] && [ \"$CHROME_VERSION\" -ge 115 ]; then echo \"Using Chrome for Testing API for version $CHROME_VERSION\"; CHROMEDRIVER_VERSION=$(curl -s \"https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VERSION\" 2>/dev/null); if [ -n \"$CHROMEDRIVER_VERSION\" ] && [ \"$CHROMEDRIVER_VERSION\" != \"Not Found\" ]; then echo \"Downloading ChromeDriver $CHROMEDRIVER_VERSION\"; wget -q \"https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip\" -O chromedriver.zip; else echo \"Chrome for Testing failed, using fixed version\"; wget -q \"https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/131.0.6778.108/linux64/chromedriver-linux64.zip\" -O chromedriver.zip; fi; else echo \"Using legacy ChromeDriver for older Chrome\"; wget -q \"https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip\" -O chromedriver.zip; fi",
    
    # Extract ChromeDriver
    "if [ -f chromedriver.zip ]; then unzip -q chromedriver.zip; if [ -d chromedriver-linux64 ]; then cp chromedriver-linux64/chromedriver /usr/local/bin/; else cp chromedriver /usr/local/bin/; fi; chmod +x /usr/local/bin/chromedriver; rm -f chromedriver.zip; rm -rf chromedriver-linux64; echo \"ChromeDriver installation completed\"; else echo \"ERROR: ChromeDriver zip file not found\"; exit 1; fi",
    
    # Verify ChromeDriver installation
    "/usr/local/bin/chromedriver --version || echo 'ChromeDriver installation failed'",
    
    # Install additional dependencies for headless Chrome
    "apt-get install -y fonts-liberation libasound2 libatk-bridge2.0-0 libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libnss3",
    
    # Clean up
    "apt-get clean && rm -rf /var/lib/apt/lists/*",
    
    # Final verification
    "echo 'Installation completed:' && ls -la /usr/bin/google-chrome-stable /usr/local/bin/chromedriver"
]

[variables]
# Environment variables for Chrome and ChromeDriver
CHROME_BIN = "/usr/bin/google-chrome-stable"
CHROMEDRIVER_PATH = "/usr/local/bin/chromedriver"
DISPLAY = ":99"
RAILWAY_ENVIRONMENT = "true" 