[phases.install]
# Simplified Chrome installation - let WebDriverManager handle ChromeDriver
cmds = [
    # Install basic tools for Chrome repository setup
    "apt-get update && apt-get install -y wget gnupg ca-certificates",
    # Add Google Chrome repository and install stable Chrome
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
    # Update and install Chrome with dependencies
    "apt-get update && apt-get install -y google-chrome-stable xvfb fonts-liberation libappindicator3-1 libasound2t64 libatk-bridge2.0-0 libnspr4 libnss3 libxss1 libxtst6 libatspi2.0-0 libgtk-3-0 libxdamage1 libdrm2 libxcomposite1 libxrandr2 && apt-get clean && rm -rf /var/lib/apt/lists/*"
]

[phases.setup]
# Set environment variables for Chrome
cmds = [
    "export CHROME_BIN=/usr/bin/google-chrome-stable",
    "export DISPLAY=:99",
    "export RAILWAY_ENVIRONMENT=production"
]

[variables]
# Environment variables for stealth Chrome operation
CHROME_BIN = "/usr/bin/google-chrome-stable"
DISPLAY = ":99"
RAILWAY_ENVIRONMENT = "production"
# Stealth environment variables
CHROME_NO_SANDBOX = "true"
CHROME_DISABLE_GPU = "true" 