[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Starting deployment...' && python manage.py collectstatic --noinput && echo 'Static files collected' && python manage.py migrate --noinput && echo 'Migrations completed' && echo 'Starting gunicorn on port:' $PORT && gunicorn stock_scraper.wsgi:application --bind 0.0.0.0:${PORT:-8000} --log-level debug" 