[build]
builder = "nixpacks"

[deploy]
startCommand = "./start_app.sh"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Chrome optimization for Railway Hobby Plan (512MB-1GB memory limit)
CHROME_BIN = "/usr/bin/google-chrome-stable"
CHROMEDRIVER_PATH = "/usr/local/bin/chromedriver"
PYTHONUNBUFFERED = "1"
MALLOC_ARENA_MAX = "1"
CHROME_ARGS = "--memory-pressure-off,--disable-features=VizDisplayCompositor,--single-process,--max_old_space_size=256"

# Hobby Plan specific optimizations
RAILWAY_MEMORY_LIMIT = "512"
NODE_OPTIONS = "--max-old-space-size=256"

# Django settings
DJANGO_SETTINGS_MODULE = "stock_scraper.settings"