[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
source = "."

[services.variables]
PORT = "8000"

# Only run the web service initially
# Celery workers can be added as separate services later 