[deploy]
startCommand = "python3 manage.py collectstatic --noinput && python3 manage.py migrate --noinput && gunicorn stock_scraper.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 